### ISSUE TITLE
Tent bug's

### ISSUE THREAD

**Issue by dridich** [bsnext/MTA-DayZ-Ultimate#209]
**Describe the bug**
Invisible tent and other locked.

**To Reproduce**
I don't know how it work, it's happened automat

**Expected behavior**
-Invisible tent: You are able to open it ,but you cant remove it
-locked tent: Cant open it,

**Screenshots or videos**
     -Locked : 
           [https://imgur.com/HkzbwtI](url)
           [https://imgur.com/EqxVKYU](url)
     -Invisible : 
           [https://imgur.com/undefined](url)
**Additional context**
i see that im not the only one who have that problem, i see a lot many clans talk about that bug in their base
and i hear too that after a long moment tent can get disappear and lose the loot inside.

**Comment by DenisChopko** [comment]
та же проблема, есть палатка, но не могу её открыть
