### ISSUE TITLE
Идеи для БсА

### ISSUE THREAD

**Issue by VorDaz1** [bsnext/MTA-DayZ-Ultimate#219]
1)Разные детали для разных видов ТС(К примеру для мотоцикла колесо для мотоцикла)
2)Оружие - добавить новое оружие для калибра 45ACP пример: UMP45
Так-же под 9мм TEC9
3)Механика GPS - Возможность если забирая с трупа убитого вами игрока забрать гпс, то гпс введенный убитым игроком
 остается
4)Баланс оружия под калибр 5.56 ибо они слишком сильные и скорострельны
5)Прокачка навыков как в обычной ГТА но не сильно существенная, допустим с недавным патчем сделали быстрый расход стамины, если прокачивать допустим назовем выносливость, то можно будет увеличить стамину на 5-20%. так-же можно увеличивать и скорость. получение опыта будет реализовано как: убил зомби "x" число опыта, также и человека или же Бандита/Героя
6)После выпрыгивания из ТС получение какого либо урона, либо перелом ноги или же Боль
7)Схроны - реализовать точно так же как и закапывание трупов только что-бы оставалась точка лута(закапывать ящики или же рюкзаки)
8)Модули - Новые прицелы, Лазер и Хамут на АС ВАЛ(Лазер - дальность поражения оружия)
9)Новые звуки для Оружия - Звуки для оружи на БСе уже слишком заезженные и однотипные, думаю пора их обновить на другие
10)Новый мотоцикл с люлькой(ducati)

**Comment by Michu2901** [comment]
@VorDaz1 
1) -
2) + new content always good but salvador have to ad new mag for that gun to work ;d
3) +
4) +
5) + -
6) +
7) -
8) + -
9) +
10) -

**Comment by VorDaz1** [comment]
Ofc i knew it

сб, 1 мая 2021 г., 18:50 Michu2901 ***@***.***>:

**Comment by menzeJl** [comment]
5) Хорошая идея, но это надо обдумывать, что бы не вышел очередной рпг фантастикл=) По мне, легче было бы это осуществить через проведённое время на сервере, например: 24ч игрового времени = 1% увеличения стамины, (И сделать исключение зачисления стамины, в момент афк, во избежание фарма) Можно было бы осуществлять эту систему по подсчету времени бега, но скорее это будет лишь лишним кодом, так как бег это 90% от гейплея на сервере, как в момент выживания так и в момент пвп.
2) Хорошим вариантом было бы добавить оружие на калибре всск(Не помню какой там калибр). Всск всегда был N 1 в том плане, что если в тебя попали, то это конечная остановка для тебя. Наверное многи замечали что маг от него можно было разряжать и немного на них полюбоваться, но что если сделать на основе этой россыпи, аналог всск, только не в  плане убийства людей, а в плане убийства машин с 1 пт(Но при этом убрать ваншот по людям). Потому что нынче почти все опытные игроки играют от машин, что считает очень имбовой тактикой, то же самое можно сказать и про вертолёт. Делать его стоит одназарядником, как cz550, а патроны будут браться тем методом который описан выше и сделать это оружие из редчайшей ветки, таких как g36 и vss.
