### ISSUE TITLE
Flying or using bugged texture

### ISSUE THREAD

**Issue by Michu2901** [bsnext/MTA-DayZ-Ultimate#222]
"Predator" probably used some glitched textures in order to camp on airdrop.
He killed like 10 players from that position. As soon as Lukas wanned to teleport to him he jumped down with parachute and died like 30 sec. later.

![image](https://user-images.githubusercontent.com/66784249/117716910-6cb94480-b1da-11eb-8f27-0f4abb6416f8.png)

Link to video: https://youtu.be/0QQNk2afw5c

**Comment by VorDaz1** [comment]
add it to VK: https://vk.com/topic-33374332_38189760
1. Report information about the violation, in the form below.
2. A screenshot that shows the essence of the complaint.
2.1. The Debug Monitor should be open and visible in the screenshot.
2.2. The screenshot must be original, not cropped, not edited.
3. The deadline for filing a complaint must be no later than 24 hours from the date of the violation.

Complaint form:
1. Server color or number.
2. Your nickname.
3. The nickname of the violator. If there are several of them, list them separated by commas.
4. Description of the violation.

**Comment by Michu2901** [comment]
@VorDaz1 That wouldnt help lmao
